export default [
  {
    name: "Brand Simmons",
    imgUrl: "./avtar/Avatar3.png",
    title: "HTML, JS, ReactJS",
    earnings: "$8,000,000",
    ernStatus: "In Progress",
    commission: "$520",
    commStatus: "Paid",
    company: "Intertico",
    designation: "Web, UI/UX Design",
    ratings: "*****",
    ratStatus: "Best Rated",
  },
  {
    name: "Jessie Clarcson ",
    imgUrl: "./avtar/Avatar1.png",
    title: "HTML, JS, ReactJS",
    earnings: "$8,000,000",
    ernStatus: "In Progress",
    commission: "$520",
    commStatus: "Paid",
    company: "Intertico",
    designation: "Web, UI/UX Design",
    ratings: "*****",
    ratStatus: "Best Rated",
  },
  {
    name: "Jessie Clarcson ",
    imgUrl: "./avtar/Avatar2.png",
    title: "HTML, JS, ReactJS",
    earnings: "$8,000,000",
    ernStatus: "In Progress",
    commission: "$520",
    commStatus: "Paid",
    company: "Intertico",
    designation: "Web, UI/UX Design",
    ratings: "*****",
    ratStatus: "Best Rated",
  },
  {
    name: "Jessie Clarcson ",
    imgUrl: "./avtar/Avatar4.png",
    title: "HTML, JS, ReactJS",
    earnings: "$8,000,000",
    ernStatus: "In Progress",
    commission: "$520",
    commStatus: "Paid",
    company: "Intertico",
    designation: "Web, UI/UX Design",
    ratings: "*****",
    ratStatus: "Best Rated",
  },
];
